### ISSUE TITLE
Error al compilar si se edita el apéndice

### ISSUE THREAD

**Issue by CFehrmann** [pachamaltese/template-tesis-uchile#1]
Estimado @pachamaltese me he cruzado con el siguiente error.
Si quitamos el chunk que resume car y gráfica pressure el documento deja de compilar.
Entrega el siguiente error:

`processing file: ./capitulos/apendice-ejemplo.Rmd
output file: tesis-rmarkdown.knit.md

! Undefined control sequence.
<argument> \hbox {\strut \includegraphics 
                                          [height=80pt]{figuras/escudo.pdf}\...
l.141 \maketitle

Error: LaTeX failed to compile tesis-rmarkdown.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See tesis-rmarkdown.log for more info.
Execution halted`

He buscado el problema, pero no he encontrado la solución.

Gracias de antemano,

Cristóbal Fehrmann

**Comment by pachadotdev** [comment]
@CFehrmann máquina, ante todo mucho éxito en la tesis. Ojo que esta plantilla tiene los márgenes, letra, espaciado, etc de la Universidad de Chile. El error que tienes es "lógico", si no hay gráficos en el documento no carga graphicx, pero el escudo de la universidad es un gráfico para latex, así que debes borrar o comentar las lineas https://github.com/pachamaltese/template-tesis-uchile/blob/master/formato-uchile.tex#L95 y https://github.com/pachamaltese/template-tesis-uchile/blob/master/formato-uchile.tex#L105 y funcionará.

**Comment by CFehrmann** [comment]
@pachamaltese Gracias te pasaste, muy buen trabajo te mandaste con este template :D
